---
image: registry.fi-ts.io/cloud-native/go-builder:latest

test-all:
  stage: test
  script:
    - make test

# This job is triggered only for a job that is triggered on tag "stable" to always have a working version in blobstore.
blobstore:
  stage: deploy
  script:
    - make
    - tar -czvf metal-networker.tar.gz -C ./bin metal-networker -C ../test-data interfaces.tpl frr.conf.tpl
    - curl -fLS https://dl.minio.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc
    - chmod +x /usr/local/bin/mc
    - mc config host add fits https://blobstore.fi-ts.io $ACCESS_KEY "${SECRET_KEY}"
    - mc cp metal-networker.tar.gz fits/cloud-native/metal-networker.tar.gz
  only:
    - stable