---
image: registry.fi-ts.io/cloud-native/go-builder:latest

test-all:
  stage: test
  script:
    - make test

.blobstore_tpl: &blobstore
  stage: deploy
  script:
    - make
    - strip bin/metal-networker
    - tar -czvf metal-networker.tar.gz -C ./bin metal-networker -C ../internal/netconf/ interfaces.firewall.tpl interfaces.machine.tpl frr.machine.tpl frr.firewall.tpl rules.v4.tpl rules.v6.tpl systemd.link.tpl systemd.network
    - .tpl hosts.tpl hostname.tpl
    - curl -fLS https://dl.minio.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc
    - chmod +x /usr/local/bin/mc
    - mc config host add fits https://blobstore.fi-ts.io $ACCESS_KEY "${SECRET_KEY}"
    - mc cp metal-networker.tar.gz fits/cloud-native/metal-networker-${suffix}.tar.gz

# This job is triggered only for a "stable" tagged branch to always have a version that is known to work properly.
stable:
  <<: *blobstore
  variables:
    suffix: stable
  only:
    - stable

# This job is triggered for every pipeline that runs in master branch to have bleeding edge version.
latest:
  <<: *blobstore
  variables:
    suffix: latest
  only:
    - master
