# https://github.com/golangci/golangci-lint#config-file
run:
  deadline: 30s
  tests: false

linters-settings:
  golint:
    min-confidence: 0.8
  gocritic:
    disabled-checks:
      - appendAssign

linters:
  enable-all: true
  disable:
    - prealloc
    - maligned
    - gochecknoglobals
    - gosec

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
    - linters:
        - gosec
      text: "G304: Potential file inclusion via variable"
